# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PocketLoa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocketLoa
  pod 'RxFlow'  

  target 'PocketLoaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PocketLoaUITests' do
    # Pods for testing
  end

end
